# Generated by Django 4.2.2 on 2023-06-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_categorie_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='categorie',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
