# Generated by Django 4.2.2 on 2023-06-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_blogpost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='published',
        ),
    ]
