# Generated by Django 4.2.2 on 2023-06-13 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_blogpost_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
