# Generated by Django 4.2.2 on 2023-06-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_blogpost_tags_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, upload_to='blogs/'),
        ),
    ]
